import type { Metadata } from "next";
import "./globals.css";
import { GlobalHeader } from "@/components/GlobalHeader";
import { GlobalFooter } from "@/components/GlobalFooter";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { fetchMenus } from "@/requests/getMenus";
import { ConfigProvider, theme } from "antd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonData = await fetchMenus();
  return (
    <html lang="en">
      <body className="pt-5 relative full">
        <AntdRegistry>
          <ConfigProvider
            theme={{ algorithm: theme.darkAlgorithm, cssVar: true }}
          >
            <GlobalHeader />
            <main className="min-h-screen flex justify-center gap-2 w-full debug">
              <aside className="h-full"></aside>
              <div className="max-w-5xl h-full w-full">
                <Breadcrumbs menus={jsonData.data} />
                {children}
              </div>
              <aside className="h-full"></aside>
            </main>
            <GlobalFooter />
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
