import type { Metadata } from 'next'
import './globals.css'
import { GlobalHeader } from '@/components/GlobalHeader'
import { GlobalFooter } from '@/components/GlobalFooter'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Breadcrumbs } from '@/components/Breadcrumbs'
import { fetchMenus } from '@/requests/getMenus'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const jsonData = await fetchMenus()
  return (
    <html lang='en'>
      <body className='pt-5 bg-gray-50 relative'>
        <AntdRegistry>
          <GlobalHeader />
          <div>
            <Breadcrumbs menus={jsonData.data} />
          </div>
          <main className='min-h-screen flex justify-center gap-2 w-full'>
            <aside className='h-full'></aside>
            <div className='max-w-7xl h-full w-full'>{children}</div>
            <aside className='h-full'></aside>
          </main>
          <GlobalFooter />
        </AntdRegistry>
      </body>
    </html>
  )
}
